# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: make-packages

on:
  push:
    branches:
      - 'master'

jobs:
  ubuntu-modules:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:

          - repo: "bionic.list"
            os: "ubuntu-18.04"
            nginx_version: "1.14.0"
            nginx_depend: "1.14.0-0ubuntu1.9"

          - repo: "focal.list"
            os: "ubuntu-20.04"
            nginx_version: "1.18.0"
            nginx_depend: "1.18.0-0ubuntu1.2"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure sources.list as ${{ matrix.repo }}
        run: sudo cp ${{ matrix.repo }} /etc/apt/sources.list

      - name: Update repo
        run: sudo apt-get update

      - name: Install build requires
        run: >
          sudo apt-get install -y \
            build-essential ca-certificates curl git gnupg2 libpcre2-dev \
            libpcre3-dev libssl-dev libz-dev lsb-release python3 ubuntu-keyring

      - name: Adding builder user
        run: sudo useradd -m -s /bin/bash builder

      - name: Create packages directory
        run: sudo mkdir -p packages && sudo chmod g+rwX packages && sudo chown :builder packages

      - name: Create packages directory
        run: (cd /home/builder && sudo -u builder apt source nginx=${{ matrix.nginx_version }})

      - name: Build packages
        run: >
          sudo -u builder python3 module-build.py \
            --nginx-src /home/builder/nginx-${{ matrix.nginx_version }} \
            --nginx-depend ${{ matrix.nginx_depend }} \
            --module-map modules.json \
            --deb-path packages \
            --deb-suffix="-ubuntu"
